### ISSUE TITLE
BUG - Redshift datediff function error with interview_enhanced, opportunity_enhanced and opportunity_stage_history models

### ISSUE THREAD

**Issue by scotthibberd** [fivetran/dbt_lever#11]
**Are you a current Fivetran customer?** 
Yes - Scott Hibberd, Infogrid. BI Analyst

**Describe the bug**
Errors in `lever__interview_enhanced`, `lever__opportunity_enhanced` and `lever__opportunity_stage_history` models due to datediff function in Redshift. This appears to be the same issue as [https://github.com/fivetran/dbt_github/issues/25](url)

```
Database Error in model lever__interview_enhanced (models/lever__interview_enhanced.sql)
  function pg_catalog.date_diff("unknown", timestamp with time zone, timestamp with time zone) does not exist
  HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
```

**Steps to reproduce**
1. Import the Lever Fivetran package
2. `dbt run`

**Expected behavior**
Models should run with no errors

**Project variables configuration**
```yml
name: 'infogrid_bi'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  lever_database: bi_database
  lever_schema: lever_fivetran 
```

**Package Version**
```yml
  - package: fivetran/lever
    version: [">=0.3.0", "<0.4.0"]
```

**Warehouse**
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
Same issue as found in this Slack thread from 25/01/22: [https://getdbt.slack.com/archives/CU4MRJ7QB/p1643125860035900](url)

**Screenshots**

**Please indicate the level of urgency** 
Not urgent, but it will require us to manually overwrite the package code until a fix is in place

**Are you interested in contributing to this package?** 
- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
